[build]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# If you want to proxy your API requests through Netlify
[[redirects]]
  from = "/api/*"
  to = "https://rajatgangwar-assignment-interactive.onrender.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}